apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - image: back
    name: app
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
