version: '3'
services:
  app:
    image: be
    container_name: app
    build: ./backend
    ports:
      - '8080:8080'
    restart: on-failure   
  frontend:
    build: ./frontend/Svelte
    image: todof
    ports:
      - "5656:5656"
    depends_on:
      - app    