version: '3'
services:
  app:
    image: back
    container_name: app
    build: ./backend
    ports:
      - '8080:8080'
    restart: on-failure   
    labels:
      kompose.service.type: LoadBalancer
  frontend:
    build: ./frontend/Svelte
    image: f
    ports:
      - '5000:5000'
    restart: on-failure  
    labels:
      kompose.service.type: LoadBalancer
    depends_on:
      - app    
 