apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
  - image: f
    name: frontend
    ports:
    - containerPort: 5000
    resources: {}
  restartPolicy: OnFailure
status: {}
